# Generated by Django 3.2.9 on 2021-11-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoping_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('title', models.CharField(max_length=225)),
                ('desc', models.TextField(default='该商品未添加详情描述', verbose_name='商品描述')),
                ('image', models.ImageField(upload_to='icon/', verbose_name='图片')),
                ('price', models.FloatField(default='0.0', verbose_name='商品价格')),
                ('count', models.IntegerField(default='0', verbose_name='商品的销售数量')),
            ],
            options={
                'db_table': 'shopping_info',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=225, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=225, verbose_name='用户密码')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('num_product', models.IntegerField(default=1, verbose_name='购物车中商品数量')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_id', to='get_info.shoping_info')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to='get_info.user_info')),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
    ]
