# Generated by Django 3.1.7 on 2021-11-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid', to='get_info.shoping_info'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to='get_info.user_info'),
        ),
    ]
