# Generated by Django 3.1.7 on 2021-11-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_info', '0002_auto_20211119_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping_info',
            name='count',
        ),
        migrations.AddField(
            model_name='shoping_info',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='商品连接地址'),
        ),
        migrations.AlterField(
            model_name='shoping_info',
            name='image',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='商品图片url'),
        ),
    ]
