# Generated by Django 3.1.7 on 2022-02-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backstage', '0005_user_info_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='payment number')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.cart', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Paymentinfor',
                'verbose_name_plural': 'Paymentinfor',
                'db_table': 'tb_payment',
            },
        ),
    ]
