# Generated by Django 3.2.8 on 2021-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='product_name',
            field=models.CharField(default='name', max_length=120),
            preserve_default=False,
        ),
    ]
