# Generated by Django 3.2.8 on 2021-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211008_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='free_returns',
        ),
        migrations.AddField(
            model_name='todo',
            name='condition',
            field=models.CharField(default=True, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='link',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='prices',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
