# Generated by Django 3.2.9 on 2021-11-18 16:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shoppingCard',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
