# Generated by Django 3.1.7 on 2021-12-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='product id')),
                ('productname', models.CharField(max_length=225, verbose_name='product name')),
                ('desc', models.TextField(default='The uploader is lazy and has nothing to introduce', max_length=288, verbose_name='产品介绍')),
                ('image', models.ImageField(upload_to='upload/%Y%m%d', verbose_name='Product Image')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
                ('change_at', models.DateTimeField(auto_now=True, verbose_name='Change the time')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='userid')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='user name')),
                ('password', models.CharField(max_length=30, verbose_name='user password')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='emial')),
                ('phonenum', models.CharField(max_length=30, unique=True, verbose_name='phone number')),
                ('superuser', models.IntegerField(choices=[(0, 'general user'), (1, 'administrator')], default=0, verbose_name='identity')),
                ('money', models.FloatField(verbose_name='')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productid', to='backstage.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='backstage.user_info')),
            ],
            options={
                'db_table': 'score',
            },
        ),
    ]
