# Generated by Django 3.1.7 on 2021-12-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='money',
        ),
    ]
