# Generated by Django 3.1.7 on 2022-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_auto_20220207_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='position',
            field=models.CharField(blank=True, default='空', max_length=200, null=True, verbose_name='地址'),
        ),
    ]
