# Generated by Django 3.1.7 on 2022-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_auto_20220308_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
